CREATE DATABASE IF NOT EXISTS AnimalShopDB;
USE AnimalShopDB;

CREATE TABLE IF NOT EXISTS animals(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	name VARCHAR(32) NULL DEFAULT NULL,
	type VARCHAR(10) NULL DEFAULT NULL,
	age INT NULL DEFAULT 0,
	price INT NULL DEFAULT 0
);

--GRANT ALL ON AliceDB.* TO 'db_user'@'%' IDENTIFIED BY 'user_password';
