version: '3'
services:
    animal_shop:
        build:
            context: ./..
            dockerfile: ./AnimalShop/Dockerfile
        ports:
            - "2200:2200"
        volumes:
            - "./config.txt:/app/config.txt"
            - "./app/log/:/app/log"
        depends_on:
            - mysql
    mysql:
        container_name: mysql
        image: mysql:5.7
        restart: always
        command: --init-file /data/application/init.sql
        environment:
            - MYSQL_DATABASE=AnimalShopDB
            - MYSQL_ROOT_PASSWORD=root_password
            - MYSQL_USER=db_user
            - MYSQL_PASSWORD=user_password
        ports:
            - "33060:3306"
        volumes:
            #- "./db_dir/data/mysql:/var/lib/mysql"
            - "./db_dir/init.sql:/data/application/init.sql"
